In [28]:
import numpy as np
import pandas as pd

In [43]:
df=pd.read_csv('iris.csv')

In [44]:
df.head()

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [45]:
df.columns=np.array((['sepal_length','sepal_width','petal_length','petal_width','flower_type']))

In [46]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width  flower_type
0           4.9          3.0           1.4          0.2  Iris-setosa
1           4.7          3.2           1.3          0.2  Iris-setosa
2           4.6          3.1           1.5          0.2  Iris-setosa
3           5.0          3.6           1.4          0.2  Iris-setosa
4           5.4          3.9           1.7          0.4  Iris-setosa

In [47]:
df['sepal_lengthmm']=[i*10 for i in df.sepal_length]

In [48]:
df.head()

,sepal_length,sepal_width,petal_length,petal_width,flower_type,sepal_lengthmm
0,4.9,3.0,1.4,0.2,Iris-setosa,49.0
1,4.7,3.2,1.3,0.2,Iris-setosa,47.0
2,4.6,3.1,1.5,0.2,Iris-setosa,46.0
3,5.0,3.6,1.4,0.2,Iris-setosa,50.0
4,5.4,3.9,1.7,0.4,Iris-setosa,54.0

In [49]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width  sepal_lengthmm
count    149.000000   149.000000    149.000000   149.000000      149.000000
mean       5.848322     3.051007      3.774497     1.205369       58.483221
std        0.828594     0.433499      1.759651     0.761292        8.285941
min        4.300000     2.000000      1.000000     0.100000       43.000000
25%        5.100000     2.800000      1.600000     0.300000       51.000000
50%        5.800000     3.000000      4.400000     1.300000       58.000000
75%        6.400000     3.300000      5.100000     1.800000       64.000000
max        7.900000     4.400000      6.900000     2.500000       79.000000

In [52]:
df=df.drop(['sepal_lengthmm'],axis=1)

In [37]:
df

     sepal_length  sepal_width  petal_length  petal_width     flower_type
0             4.9          3.0           1.4          0.2     Iris-setosa
1             4.7          3.2           1.3          0.2     Iris-setosa
2             4.6          3.1           1.5          0.2     Iris-setosa
3             5.0          3.6           1.4          0.2     Iris-setosa
4             5.4          3.9           1.7          0.4     Iris-setosa
..            ...          ...           ...          ...             ...
144           6.7          3.0           5.2          2.3  Iris-virginica
145           6.3          2.5           5.0          1.9  Iris-virginica
146           6.5          3.0           5.2          2.0  Iris-virginica
147           6.2          3.4           5.4          2.3  Iris-virginica
148           5.9          3.0           5.1          1.8  Iris-virginica

[149 rows x 5 columns]

In [50]:
df['sepal_area']=[i*j for i,j in zip(df.sepal_length,df.sepal_width)]

In [54]:
df.head()

,sepal_length,sepal_width,petal_length,petal_width,flower_type,sepal_area
0,4.9,3.0,1.4,0.2,Iris-setosa,14.70
1,4.7,3.2,1.3,0.2,Iris-setosa,15.04
2,4.6,3.1,1.5,0.2,Iris-setosa,14.26
3,5.0,3.6,1.4,0.2,Iris-setosa,18.00
4,5.4,3.9,1.7,0.4,Iris-setosa,21.06

In [55]:
df['petal_area']=[i*j for i,j in zip(df.petal_length,df.petal_width)]

In [56]:
df.head()

,sepal_length,sepal_width,petal_length,petal_width,flower_type,sepal_area,petal_area
0,4.9,3.0,1.4,0.2,Iris-setosa,14.70,0.28
1,4.7,3.2,1.3,0.2,Iris-setosa,15.04,0.26
2,4.6,3.1,1.5,0.2,Iris-setosa,14.26,0.30
3,5.0,3.6,1.4,0.2,Iris-setosa,18.00,0.28
4,5.4,3.9,1.7,0.4,Iris-setosa,21.06,0.68

In [57]:
df[df.flower_type=='Iris-setosa']

,sepal_length,sepal_width,petal_length,petal_width,flower_type,sepal_area,petal_area
0,4.9,3.0,1.4,0.2,Iris-setosa,14.70,0.28
1,4.7,3.2,1.3,0.2,Iris-setosa,15.04,0.26
2,4.6,3.1,1.5,0.2,Iris-setosa,14.26,0.30
3,5.0,3.6,1.4,0.2,Iris-setosa,18.00,0.28
4,5.4,3.9,1.7,0.4,Iris-setosa,21.06,0.68
5,4.6,3.4,1.4,0.3,Iris-setosa,15.64,0.42
6,5.0,3.4,1.5,0.2,Iris-setosa,17.00,0.30
7,4.4,2.9,1.4,0.2,Iris-setosa,12.76,0.28
8,4.9,3.1,1.5,0.1,Iris-setosa,15.19,0.15
9,5.4,3.7,1.5,0.2,Iris-setosa,19.98,0.30
10,4.8,3.4,1.6,0.2,Iris-setosa,16.32,0.32
11,4.8,3.0,1.4,0.1,Iris-setosa,14.40,0.14
12,4.3,3.0,1.1,0.1,Iris-setosa,12.90,0.11
13,5.8,4.0,1.2,0.2,Iris-setosa,23.20,0.24
14,5.7,4.4,1.5,0.4,Iris-setosa,25.08,0.60
15,5.4,3.9,1.3,0.4,Iris-setosa,21.06,0.52
16,5.1,3.5,1.4,0.3,Iris-setosa,17.85,0.42
17,5.7,3.8,1.7,0.3,Iris-setosa,21.66,0.51
18,5.1,3.8,1.5,0.3,Iris-setosa,19.38,0.45
19,5.4,3.4,1.7,0.2,Iris-setosa,18.36,0.34
20,5.1,3.7,1.5,0.4,Iris-setosa,18.87,0.60
21,4.6,3.6,1.0,0.2,Iris-setosa,16.56,0.20
22,5.1,3.3,1.7,0.5,Iris-setosa,16.83,0.85
23,4.8,3.4,1.9,0.2,Iris-setosa,16.32,0.38
24,5.0,3.0,1.6,0.2,Iris-setosa,15.00,0.32
25,5.0,3.4,1.6,0.4,Iris-setosa,17.00,0.64
26,5.2,3.5,1.5,0.2,Iris-setosa,18.20,0.30
27,5.2,3.4,1.4,0.2,Iris-setosa,17.68,0.28
28,4.7,3.2,1.6,0.2,Iris-setosa,15.04,0.32
29,4.8,3.1,1.6,0.2,Iris-setosa,14.88,0.32
30,5.4,3.4,1.5,0.4,Iris-setosa,18.36,0.60
31,5.2,4.1,1.5,0.1,Iris-setosa,21.32,0.15
32,5.5,4.2,1.4,0.2,Iris-setosa,23.10,0.28
33,4.9,3.1,1.5,0.1,Iris-setosa,15.19,0.15
34,5.0,3.2,1.2,0.2,Iris-setosa,16.00,0.24
35,5.5,3.5,1.3,0.2,Iris-setosa,19.25,0.26
36,4.9,3.1,1.5,0.1,Iris-setosa,15.19,0.15
37,4.4,3.0,1.3,0.2,Iris-setosa,13.20,0.26
38,5.1,3.4,1.5,0.2,Iris-setosa,17.34,0.30
39,5.0,3.5,1.3,0.3,Iris-setosa,17.50,0.39
40,4.5,2.3,1.3,0.3,Iris-setosa,10.35,0.39
41,4.4,3.2,1.3,0.2,Iris-setosa,14.08,0.26
42,5.0,3.5,1.6,0.6,Iris-setosa,17.50,0.96
43,5.1,3.8,1.9,0.4,Iris-setosa,19.38,0.76
44,4.8,3.0,1.4,0.3,Iris-setosa,14.40,0.42
45,5.1,3.8,1.6,0.2,Iris-setosa,19.38,0.32
46,4.6,3.2,1.4,0.2,Iris-setosa,14.72,0.28
47,5.3,3.7,1.5,0.2,Iris-setosa,19.61,0.30
48,5.0,3.3,1.4,0.2,Iris-setosa,16.50,0.28

In [58]:
df[df.flower_type=='Iris-setosa'].describe()

,sepal_length,sepal_width,petal_length,petal_width,sepal_area,petal_area
count,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000
mean,5.004082,3.416327,1.465306,0.244898,17.195714,0.364490
std,0.355879,0.384787,0.175061,0.108130,2.976767,0.184753
min,4.300000,2.300000,1.000000,0.100000,10.350000,0.110000
25%,4.800000,3.100000,1.400000,0.200000,15.040000,0.260000
50%,5.000000,3.400000,1.500000,0.200000,17.000000,0.300000
75%,5.200000,3.700000,1.600000,0.300000,19.250000,0.420000
max,5.800000,4.400000,1.900000,0.600000,25.080000,0.960000

In [60]:
set(df.flower_type) #distinct types

{'Iris-setosa', 'Iris-versicolor', 'Iris-virginica'}

In [61]:
df[df.flower_type=='Iris-versicolor']

,sepal_length,sepal_width,petal_length,petal_width,flower_type,sepal_area,petal_area
49,7.0,3.2,4.7,1.4,Iris-versicolor,22.40,6.58
50,6.4,3.2,4.5,1.5,Iris-versicolor,20.48,6.75
51,6.9,3.1,4.9,1.5,Iris-versicolor,21.39,7.35
52,5.5,2.3,4.0,1.3,Iris-versicolor,12.65,5.20
53,6.5,2.8,4.6,1.5,Iris-versicolor,18.20,6.90
54,5.7,2.8,4.5,1.3,Iris-versicolor,15.96,5.85
55,6.3,3.3,4.7,1.6,Iris-versicolor,20.79,7.52
56,4.9,2.4,3.3,1.0,Iris-versicolor,11.76,3.30
57,6.6,2.9,4.6,1.3,Iris-versicolor,19.14,5.98
58,5.2,2.7,3.9,1.4,Iris-versicolor,14.04,5.46
59,5.0,2.0,3.5,1.0,Iris-versicolor,10.00,3.50
60,5.9,3.0,4.2,1.5,Iris-versicolor,17.70,6.30
61,6.0,2.2,4.0,1.0,Iris-versicolor,13.20,4.00
62,6.1,2.9,4.7,1.4,Iris-versicolor,17.69,6.58
63,5.6,2.9,3.6,1.3,Iris-versicolor,16.24,4.68
64,6.7,3.1,4.4,1.4,Iris-versicolor,20.77,6.16
65,5.6,3.0,4.5,1.5,Iris-versicolor,16.80,6.75
66,5.8,2.7,4.1,1.0,Iris-versicolor,15.66,4.10
67,6.2,2.2,4.5,1.5,Iris-versicolor,13.64,6.75
68,5.6,2.5,3.9,1.1,Iris-versicolor,14.00,4.29
69,5.9,3.2,4.8,1.8,Iris-versicolor,18.88,8.64
70,6.1,2.8,4.0,1.3,Iris-versicolor,17.08,5.20
71,6.3,2.5,4.9,1.5,Iris-versicolor,15.75,7.35
72,6.1,2.8,4.7,1.2,Iris-versicolor,17.08,5.64
73,6.4,2.9,4.3,1.3,Iris-versicolor,18.56,5.59
74,6.6,3.0,4.4,1.4,Iris-versicolor,19.80,6.16
75,6.8,2.8,4.8,1.4,Iris-versicolor,19.04,6.72
76,6.7,3.0,5.0,1.7,Iris-versicolor,20.10,8.50
77,6.0,2.9,4.5,1.5,Iris-versicolor,17.40,6.75
78,5.7,2.6,3.5,1.0,Iris-versicolor,14.82,3.50
79,5.5,2.4,3.8,1.1,Iris-versicolor,13.20,4.18
80,5.5,2.4,3.7,1.0,Iris-versicolor,13.20,3.70
81,5.8,2.7,3.9,1.2,Iris-versicolor,15.66,4.68
82,6.0,2.7,5.1,1.6,Iris-versicolor,16.20,8.16
83,5.4,3.0,4.5,1.5,Iris-versicolor,16.20,6.75
84,6.0,3.4,4.5,1.6,Iris-versicolor,20.40,7.20
85,6.7,3.1,4.7,1.5,Iris-versicolor,20.77,7.05
86,6.3,2.3,4.4,1.3,Iris-versicolor,14.49,5.72
87,5.6,3.0,4.1,1.3,Iris-versicolor,16.80,5.33
88,5.5,2.5,4.0,1.3,Iris-versicolor,13.75,5.20
89,5.5,2.6,4.4,1.2,Iris-versicolor,14.30,5.28
90,6.1,3.0,4.6,1.4,Iris-versicolor,18.30,6.44
91,5.8,2.6,4.0,1.2,Iris-versicolor,15.08,4.80
92,5.0,2.3,3.3,1.0,Iris-versicolor,11.50,3.30
93,5.6,2.7,4.2,1.3,Iris-versicolor,15.12,5.46
94,5.7,3.0,4.2,1.2,Iris-versicolor,17.10,5.04
95,5.7,2.9,4.2,1.3,Iris-versicolor,16.53,5.46
96,6.2,2.9,4.3,1.3,Iris-versicolor,17.98,5.59
97,5.1,2.5,3.0,1.1,Iris-versicolor,12.75,3.30
98,5.7,2.8,4.1,1.3,Iris-versicolor,15.96,5.33

In [62]:
df[df.flower_type=='Iris-versicolor'].describe()

,sepal_length,sepal_width,petal_length,petal_width,sepal_area,petal_area
count,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,5.936000,2.770000,4.260000,1.326000,16.526200,5.720400
std,0.516171,0.313798,0.469911,0.197753,2.866882,1.368403
min,4.900000,2.000000,3.000000,1.000000,10.000000,3.300000
25%,5.600000,2.525000,4.000000,1.200000,14.347500,4.860000
50%,5.900000,2.800000,4.350000,1.300000,16.385000,5.615000
75%,6.300000,3.000000,4.600000,1.500000,18.495000,6.750000
max,7.000000,3.400000,5.100000,1.800000,22.400000,8.640000

In [63]:
df[df.flower_type=='Iris-virginica'].describe()

,sepal_length,sepal_width,petal_length,petal_width,sepal_area,petal_area
count,50.00000,50.000000,50.000000,50.00000,50.000000,50.000000
mean,6.58800,2.974000,5.552000,2.02600,19.684600,11.296200
std,0.63588,0.322497,0.551895,0.27465,3.458783,2.157412
min,4.90000,2.200000,4.500000,1.40000,12.250000,7.500000
25%,6.22500,2.800000,5.100000,1.80000,17.430000,9.717500
50%,6.50000,3.000000,5.550000,2.00000,20.060000,11.445000
75%,6.90000,3.175000,5.875000,2.30000,21.412500,12.790000
max,7.90000,3.800000,6.900000,2.50000,30.020000,15.870000

In [ ]:
#areas:
#setosa     =17.195714  0.364490
#virginica =19.684600   11.296200
#versicolor=16.526200   5.720400

In [89]:
def getflower(sl,sw,pl,pw):
    sa=sl*sw
    pa=pl*pw
    diff1=abs(11.29-pa)
    diff2=abs(0.36-pa)
    diff3=abs(5.72-pa)
    if(diff3<=diff2 and diff3<=diff1):
        return 'Iris-versicolor'
    if(diff2<=diff1 and diff2<=diff3):
        return 'Iris-setosa'
    if(diff1<=diff2 and diff1<=diff3):
        return 'Iris-virginica'

In [67]:
df.head()

,sepal_length,sepal_width,petal_length,petal_width,flower_type,sepal_area,petal_area
0,4.9,3.0,1.4,0.2,Iris-setosa,14.70,0.28
1,4.7,3.2,1.3,0.2,Iris-setosa,15.04,0.26
2,4.6,3.1,1.5,0.2,Iris-setosa,14.26,0.30
3,5.0,3.6,1.4,0.2,Iris-setosa,18.00,0.28
4,5.4,3.9,1.7,0.4,Iris-setosa,21.06,0.68

In [80]:
df['flower_predicted']=[getflower(a,b,c,d)for a,b,c,d in zip(df.sepal_length,df.sepal_width, df.petal_length,df.petal_length)]

In [76]:
df.head()

,sepal_length,sepal_width,petal_length,petal_width,flower_type,sepal_area,petal_area,flower_predicted
0,4.9,3.0,1.4,0.2,Iris-setosa,14.70,0.28,Iris setosa
1,4.7,3.2,1.3,0.2,Iris-setosa,15.04,0.26,Iris setosa
2,4.6,3.1,1.5,0.2,Iris-setosa,14.26,0.30,Iris setosa
3,5.0,3.6,1.4,0.2,Iris-setosa,18.00,0.28,Iris setosa
4,5.4,3.9,1.7,0.4,Iris-setosa,21.06,0.68,Iris setosa

In [90]:
df[df.flower_type==df.flower_predicted]

,sepal_length,sepal_width,petal_length,petal_width,flower_type,sepal_area,petal_area,flower_predicted
0,4.9,3.0,1.4,0.2,Iris-setosa,14.70,0.28,Iris-setosa
1,4.7,3.2,1.3,0.2,Iris-setosa,15.04,0.26,Iris-setosa
2,4.6,3.1,1.5,0.2,Iris-setosa,14.26,0.30,Iris-setosa
3,5.0,3.6,1.4,0.2,Iris-setosa,18.00,0.28,Iris-setosa
4,5.4,3.9,1.7,0.4,Iris-setosa,21.06,0.68,Iris-setosa
...,...,...,...,...,...,...,...,...
144,6.7,3.0,5.2,2.3,Iris-virginica,20.10,11.96,Iris-virginica
145,6.3,2.5,5.0,1.9,Iris-virginica,15.75,9.50,Iris-virginica
146,6.5,3.0,5.2,2.0,Iris-virginica,19.50,10.40,Iris-virginica
147,6.2,3.4,5.4,2.3,Iris-virginica,21.08,12.42,Iris-virginica
148,5.9,3.0,5.1,1.8,Iris-virginica,17.70,9.18,Iris-virginica